2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_setup.py:_flush():67] Configure stats pid to 23093
2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_setup.py:_flush():67] Loading settings from /home/ray/.config/wandb/settings
2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_setup.py:_flush():67] Loading settings from /home/ray/Repositories/pointnetv2/wandb/settings
2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-24 09:21:07,333 INFO    MainThread:23093 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/offline-run-20250324_092107-3jlowjzk/logs/debug.log
2025-03-24 09:21:07,334 INFO    MainThread:23093 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/offline-run-20250324_092107-3jlowjzk/logs/debug-internal.log
2025-03-24 09:21:07,334 INFO    MainThread:23093 [wandb_init.py:init():761] calling init triggers
2025-03-24 09:21:07,334 INFO    MainThread:23093 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'task': None, 'modelnet_version': 'ModelNet10', 'sample_points': 2048, 'ratio1': 0.75, 'ratio2': 0.33, 'radius1': 0.48, 'radius2': 0.24, 'epochs': 20, 'lr': 0.001, 'dropout': 0.1, 'batch_size': 16, 'num_workers': 6, '_wandb': {}}
2025-03-24 09:21:07,334 INFO    MainThread:23093 [wandb_init.py:init():784] starting backend
2025-03-24 09:21:07,537 INFO    MainThread:23093 [wandb_init.py:init():788] sending inform_init request
2025-03-24 09:21:07,539 INFO    MainThread:23093 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 09:21:07,539 INFO    MainThread:23093 [wandb_init.py:init():798] backend started and connected
2025-03-24 09:21:07,539 INFO    MainThread:23093 [wandb_init.py:init():891] updated telemetry
2025-03-24 09:21:07,540 INFO    MainThread:23093 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-24 09:21:07,643 INFO    MainThread:23093 [wandb_init.py:init():990] starting run threads in backend
2025-03-24 09:21:07,673 INFO    MainThread:23093 [wandb_run.py:_console_start():2375] atexit reg
2025-03-24 09:21:07,673 INFO    MainThread:23093 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-24 09:21:07,673 INFO    MainThread:23093 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-24 09:21:07,673 INFO    MainThread:23093 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-24 09:21:07,673 INFO    MainThread:23093 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-24 09:21:50,687 INFO    MsgRouterThr:23093 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
2025-03-24 09:21:50,932 ERROR   MainThread:23093 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 275, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ImportError: sys.meta_path is None, Python is likely shutting down
2025-03-24 09:21:50,942 ERROR   MainThread:23093 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 275, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ImportError: sys.meta_path is None, Python is likely shutting down
2025-03-24 09:21:50,942 ERROR   MainThread:23093 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/home/ray/miniconda3/envs/pyg_env/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py", line 275, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
                              ^^^^^^^^^^^^^^^^^
ImportError: sys.meta_path is None, Python is likely shutting down
